language: android
sudo: required
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a
  global:
    - ADB_INSTALL_TIMEOUT=10

android:
  components:
    - tools
    - tools
    - android-22
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-android-support
    - sys-img-$ANDROID_ABI-$ANDROID_TARGET
before_install:
  - chmod +x gradlew
  - cp -r config/ci/licenses $ANDROID_HOME/
  
before_script:
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

script:
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
  - ./gradlew check connectedCheck -PdisablePreDex --stacktrace

